name: face_detection_tflite_example
description: Example app for face_detection_tflite
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image: ^4.5.4
  image_picker: ^1.2.0
  file_selector: ^1.0.3
  file_selector_macos: ^0.9.4+2
  face_detection_tflite:
    path: ../
  flutter_colorpicker: ^1.1.0

flutter:
  uses-material-design: true